version: '2'
services:
  mysql:
    image: mysql:5.7
    command: mysqld --datadir=/tmp/mysqldata
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: kolide
      MYSQL_USER: kolide
      MYSQL_PASSWORD: kolide
    volumes:
      - .:/tmp
    expose:
      - "3306"

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - "1025"
    ports:
      - "8025:8025"

  redis:
    image: redis:3.2.4
    expose:
      - "6379"

  kolide:
    image: kolide/kolide:latest
    command: sh -c "./kolide prepare db --config=/tmp/kolide.yml && ./kolide serve --config=/tmp/kolide.yml"
    depends_on:
      - mysql
      - mailhog
      - redis
    volumes:
      - .:/tmp
    ports:
      - "8412:8412"